name: toys
services:
  # backend:
  #   build: backend
  #   ports:
  #     - 3000:3000

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      # - ./scripts/db/postgresql.conf:/usr/share/postgresql/15/postgresql.conf
      - db-data:/var/lib/postgresql/data

  db-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - 5050:80

volumes:
  db-data: {}
