name: toys
services:
  backend:
    build: backend

  db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # POSTGRES_DB: toys
    ports:
      - 5432:5432

  db-admin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 4sizn@naver.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - 5050:80
